# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pic_rc
import time
import os


class UI_D(QtWidgets.QMainWindow):
    def __init__(self, fa, ADC):
        super(UI_D, self).__init__()
        self.is_valid = True # 当前功能检测结果是否符合要求
        self.DATA = {} # 保存当前页面的数据信息
        self.father = fa # 父界面，即系统主界面
        self.path = './tmp/d.txt' # 当前功能实验结果临时文件
        self.ADC = ADC # 压力传感器
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 410)
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(0, 0, 451, 81))
        self.textBrowser_1.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 95, 251, 84))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.frame_1 = QtWidgets.QFrame(Form)
        self.frame_1.setGeometry(QtCore.QRect(0, 90, 271, 90))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName("frame_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 190, 201, 91))
        self.textBrowser_2.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(300, 99, 141, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(289, 95, 161, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(205, 190, 251, 90))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(210, 195, 241, 84))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_t_min_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_t_min_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_min_2.setObjectName("label_t_min_2")
        self.gridLayout_3.addWidget(self.label_t_min_2, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setMinimumSize(QtCore.QSize(75, 0))
        self.label_8.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_t_max_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_t_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_max_2.setObjectName("label_t_max_2")
        self.gridLayout_3.addWidget(self.label_t_max_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(212, 310, 241, 84))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setMinimumSize(QtCore.QSize(75, 0))
        self.label_12.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(206, 305, 251, 90))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 304, 201, 91))
        self.textBrowser_3.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_png = QtWidgets.QLabel(Form)
        self.label_png.setGeometry(QtCore.QRect(460, 0, 330, 210))
        self.label_png.setText("")
        self.label_png.setPixmap(QtGui.QPixmap(":/resources/device.png"))
        self.label_png.setScaledContents(True)
        self.label_png.setObjectName("label_png")
        self.label_conform = QtWidgets.QLabel(Form)
        self.label_conform.setGeometry(QtCore.QRect(660, 220, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_conform.setFont(font)
        self.label_conform.setStyleSheet("")
        self.label_conform.setText("")
        self.label_conform.setObjectName("label_conform")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(460, 260, 330, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(710, 370, 80, 30))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(460, 370, 80, 30))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(460, 220, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(590, 370, 80, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.frame_1.raise_()
        self.textBrowser_1.raise_()
        self.gridLayoutWidget.raise_()
        self.textBrowser_2.raise_()
        self.gridLayoutWidget_2.raise_()
        self.frame_3.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        self.textBrowser_3.raise_()
        self.label_png.raise_()
        self.label_conform.raise_()
        self.textBrowser.raise_()
        self.pushButton_return.raise_()
        self.pushButton_clear.raise_()
        self.pushButton.raise_()
        self.pushButton_save.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("压力控制抗干扰能力检测")
        self.textBrowser_1.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(1)按下大号硬质圆柱课锁定支撑杆按钮，使其处于撑开状态，将大号或中号止血袖带卷扎在其上，松紧适中</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)按图连接止血带机和标准器，打开连接压力标准器和止血袖带气路开关3和4，关闭其他气路开关</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(3)设置止血带机工作压力为22kPa</p></body></html>"))
        self.label_3.setText(_translate("Form", "输入止血带机参数"))
        self.label_5.setText(_translate("Form", "压力控制精度(默认1kPa)"))
        self.label_4.setText(_translate("Form", "扰动恢复时间(默认值2s)"))
        self.pushButton_2.setText(_translate("Form", "确认"))
        self.textBrowser_2.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)启动止血带机止血模式，等待压力稳定</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)快速按压可锁定支撑杆按钮，使其至收回状态</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(3)未出结果前不要进行其他操作</p></body></html>"))
        self.label_2.setText(_translate("Form", "压力测量示值(kPa)"))
        self.label_t_min_2.setText(_translate("Form", "降压扰动恢复时间(s)"))
        self.pushButton_3.setText(_translate("Form", "开始测试"))
        self.label_6.setText(_translate("Form", "最小扰动测试"))
        self.label_t_max_2.setText(_translate("Form", "扰动压力最小值(kPa)"))
        self.label_9.setText(_translate("Form", "最大扰动测试"))
        self.label_11.setText(_translate("Form", "升压扰动恢复时间(s)"))
        self.label_10.setText(_translate("Form", "扰动压力最大值(kPa)"))
        self.pushButton_4.setText(_translate("Form", "开始测试"))
        self.textBrowser_3.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)快速按压可锁定支撑杆按钮，使其至支撑状态</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)未出结果前不要进行其他操作</p></body></html>"))
        self.pushButton_return.setText(_translate("Form", "返回"))
        self.pushButton_clear.setText(_translate("Form", "还原"))
        self.pushButton.setText(_translate("Form", "检测结果"))
        self.pushButton_save.setText(_translate("Form", "保存"))

        # -----------------------------------初始化，调整文本框可视-------------------------------------------
        self.label_conform.hide()
        self.textBrowser.hide()
        # --------------------------------------------------------------------------------------------------

        # ----------------------------------------绑定按钮槽函数---------------------------------------------
        self.pushButton_2.clicked.connect(self.d_1)
        self.pushButton_3.clicked.connect(self.d_2)
        self.pushButton_4.clicked.connect(self.d_3)
        self.pushButton.clicked.connect(self.d_over)
        self.pushButton_clear.clicked.connect(self.d_clear)
        self.pushButton_save.clicked.connect(self.save_file)
        # --------------------------------------------------------------------------------------------------

        # 返回主程序
        self.pushButton_return.clicked.connect(lambda: {self.father.show(), self.close()})

        # 创建一个临时txt
        if os.path.exists(self.path):
            os.remove(self.path)
        file = open(self.path, 'w')
        file.close()

    def d_1(self):
        # 输入相应参数
        # 如果是数字，先判断是否填写了，如果填写了再判断是否为数字形式
        # 不符合要求进行对话框提醒
        if self.lineEdit.text() == '':
            self.DATA['T_dr'] = 2
            self.lineEdit.setText("2")
        else:
            if self.lineEdit.text().replace(".", "").isdigit():
                self.DATA['T_dr'] = float(self.lineEdit.text())
            else:
                QMessageBox.information(self, 'info', '请输入正确的参数')
                return

        if self.lineEdit_2.text() == '':
            self.DATA['P_ac'] = 1
            self.lineEdit_2.setText("1")
        else:
            if self.lineEdit_2.text().replace(".", "").isdigit():
                self.DATA['P_ac'] = float(self.lineEdit_2.text())
            else:
                QMessageBox.information(self, 'info', '请输入正确的参数')
                return

    def d_2(self):
        # 最小扰动测试
        cnt = 0 # 循环次数
        while True:
            cnt += 1
            ps = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
            self.label.setText(f'{ps:.2f}' + "kPa")
            if ps <= 20:
                # 压力值达标，测试扰动恢复时间
                ps_min = ps
                while True:
                    p1 = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
                    if p1 < ps:
                        # 如果比最小值小，更新最小值
                        ps_min = min(ps_min, p1)
                    else:
                        # 但如果比第一个值ps大
                        # 说明增压了
                        self.label_7.setText(f'{ps_min:.2f}')
                        break

                time_start = time.time()
                while True:
                    # 循环判断扰动是否恢复
                    time.sleep(0.5)
                    ps = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
                    self.label.setText(f'{ps:.2f}' + "kPa")
                    if abs(ps - 22) <= self.DATA['P_ac']:
                        time_end = time.time()
                        break
                    
                t_drd = (time_end - time_start) / (20 - ps_min) * 2
                if abs(t_drd) <= 2:
                    self.label_8.setText(f'{t_drd:.2f}')
                    return
                else:
                    self.is_valid = False
                    self.textBrowser.append("最小扰动测试不符合要求")
            else:
                # 如果循环4次还未达标
                # 那么就提醒，重新操作
                if cnt <= 4:
                    time.sleep(0.5)
                else:
                    QMessageBox.information(self, 'info',
                                            '按止血带机放气按钮，并按压可锁定支撑杆按钮，使其回到撑开状态，重新调节止血袖带卷扎松紧程度')
                    return

    def d_3(self):
        # 最大扰动测试
        # 与d_2()类似
        cnt = 0
        while True:
            cnt += 1
            ps = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
            self.label.setText(f'{ps:.2f}' + "kPa")
            if ps >= 24:
                # 压力值达标，测试扰动恢复时间
                # 标准器压力增加否， 没懂？
                ps_max = ps
                while True:
                    p1 = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
                    if p1 > ps:
                        ps_max = max(ps_max, p1)
                    else:
                        # 说明降压了
                        self.label_12.setText(f'{ps_max:.2f}')
                        break

                time_start = time.time()
                while True:
                    time.sleep(0.5)
                    ps = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
                    self.label.setText(f'{ps:.2f}' + "kPa")
                    if abs(ps - 22) <= self.DATA['P_ac']:
                        time_end = time.time()
                        break
                    
                t_drd = (time_end - time_start) / (ps_max - 24) * 2
                if abs(t_drd) <= 2:
                    self.label_13.setText(f'{t_drd:.2f}')
                    return
                else:
                    self.is_valid = False
                    self.textBrowser.append("最大扰动测试不符合要求")
            else:
                if cnt <= 4:
                    time.sleep(0.5)
                else:
                    QMessageBox.information(self, 'info',
                                            '按止血带机放气按钮，并按压可锁定支撑杆按钮，使其回到收回状态，重新调节止血袖带卷扎松紧程度')
                    return

    def d_over(self):
        # 查询检测结果按钮
        if self.is_valid:
            self.label_conform.setText("符合要求")
            self.label_conform.setStyleSheet("color: green ")
        else:
            self.label_conform.setText("不符合要求")
            self.label_conform.setStyleSheet("color: red ")
            self.textBrowser.show()
        self.label_conform.show()

    def d_clear(self):
        # 还原按钮
        self.is_valid = True
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.textBrowser.clear()
        self.textBrowser.hide()
        self.label_conform.hide()
        self.label.clear()
        self.label_7.clear()
        self.label_8.clear()
        self.label_12.clear()
        self.label_13.clear()
    
    def save_file(self):
        # 保存文件
        with open(self.path, 'w', encoding='utf-8') as writers:
            if self.is_valid:
                # 符合要求
                writers.write('    符合要求\n')
            else:
                writers.write('    不符合要求,备注: ')
                content = self.textBrowser.toPlainText().replace('\n', ';    ')
                writers.write(content)
    
    def closeEvent(self, event):
        # 重载界面关闭事件
        self.father.resize(800, 400)
        event.accept()


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     gui = UI_D()
#     gui.show()
#     sys.exit(app.exec_())

