# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pic_rc
import time
import os


class UI_F(QtWidgets.QMainWindow):
    def __init__(self, fa, ADC):
        super(UI_F, self).__init__()
        self.DATA = {} # 保存当前页面的数据信息
        self.father = fa # 父界面，即系统主界面
        self.path = './tmp/f.txt' # 当前功能实验结果临时文件
        self.ADC = ADC # 压力传感器
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 360)
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(0, 0, 451, 61))
        self.textBrowser_1.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 70, 151, 81))
        self.textBrowser_2.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(167, 114, 271, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(160, 70, 291, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 6, 271, 31))
        self.label_2.setObjectName("label_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 170, 151, 81))
        self.textBrowser_3.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(160, 170, 221, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(167, 174, 211, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 270, 151, 81))
        self.textBrowser_4.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(167, 276, 211, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_png = QtWidgets.QLabel(Form)
        self.label_png.setGeometry(QtCore.QRect(460, 0, 330, 210))
        self.label_png.setText("")
        self.label_png.setPixmap(QtGui.QPixmap(":/resources/device.png"))
        self.label_png.setScaledContents(True)
        self.label_png.setObjectName("label_png")
        self.frame_1 = QtWidgets.QFrame(Form)
        self.frame_1.setGeometry(QtCore.QRect(460, 220, 331, 90))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName("frame_1")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(466, 225, 321, 84))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_in_para = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_in_para.setObjectName("label_in_para")
        self.gridLayout.addWidget(self.label_in_para, 0, 0, 1, 1)
        self.label_t_min = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_t_min.setObjectName("label_t_min")
        self.gridLayout.addWidget(self.label_t_min, 2, 0, 1, 1)
        self.label_t_max = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_t_max.setObjectName("label_t_max")
        self.gridLayout.addWidget(self.label_t_max, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(460, 320, 80, 30))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(710, 320, 80, 30))
        self.pushButton_return.setObjectName("pushButton_return")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(160, 270, 221, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(590, 320, 80, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.textBrowser_1.raise_()
        self.textBrowser_2.raise_()
        self.gridLayoutWidget_2.raise_()
        self.textBrowser_3.raise_()
        self.frame_3.raise_()
        self.gridLayoutWidget_3.raise_()
        self.textBrowser_4.raise_()
        self.gridLayoutWidget_4.raise_()
        self.label_png.raise_()
        self.frame_1.raise_()
        self.gridLayoutWidget.raise_()
        self.pushButton_clear.raise_()
        self.pushButton_return.raise_()
        self.pushButton_save.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("压力设置值与袖带压力示值一致性检测")
        self.textBrowser_1.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(1)按图连接止血带机和标准器</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)将小号止血袖带卷扎在合适尺寸的硬质圆柱上，松紧适宜</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(3)打开压力标准器和止血袖带气路开关3和4，关闭其他开关</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)在止血带机上设置工作压力为50kPa</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)在标准器上输入压力基准为50kPa</p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "确认"))
        self.label_2.setText(_translate("Form", "标准器压力基准值(默认50kPa)"))
        self.textBrowser_3.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)启动止血带机加压操作，并等待达到预置值</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)启动标准器1min计时</p></body></html>"))
        self.pushButton.setText(_translate("Form", "止血压力达到预置值时\n"
                                                   "计时器启动按键"))
        self.label.setText(_translate("Form", "1min倒计时显示"))
        self.textBrowser_4.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)待计时完成后，采集为期10s的20个实时压力测量值</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)计算止血带机与压力标准器最大压力值和偏差值</p></body></html>"))

        self.label_in_para.setText(_translate("Form", "预置值kPa"))
        self.label_t_min.setText(_translate("Form", "差值kPa"))
        self.label_t_max.setText(_translate("Form", "偏离预置值最大的示值kPa"))
        self.pushButton_clear.setText(_translate("Form", "还原"))
        self.pushButton_return.setText(_translate("Form", "返回"))
        self.pushButton_save.setText(_translate("Form", "保存"))

        # ----------------------------------------绑定按钮槽函数---------------------------------------------
        self.pushButton_3.clicked.connect(self.f_1)
        self.pushButton.clicked.connect(self.f_2)
        self.pushButton_clear.clicked.connect(self.f_clear)
        self.pushButton_save.clicked.connect(self.save_file)
        # --------------------------------------------------------------------------------------------------


        # 返回主程序
        self.pushButton_return.clicked.connect(lambda: {self.father.show(), self.close()})

        # 创建一个临时txt
        if os.path.exists(self.path):
            os.remove(self.path)
        file = open(self.path, 'w')
        file.close()

    def f_1(self):
        # 输入相应参数
        # 如果是数字，先判断是否填写了，如果填写了再判断是否为数字形式
        # 不符合要求进行对话框提醒
        if self.lineEdit.text() == '':
            self.DATA['基准值'] = 50.0
            self.lineEdit.setText("50")
        else:
            if self.lineEdit.text().replace(".", "").isdigit():
                self.DATA['基准值'] = float(self.lineEdit.text())
            else:
                QMessageBox.information(self, 'info', '请输入正确参数')
                return

    def f_2(self):
        # 一分钟倒计时
        time_start = time.time()
        while True:
            time.sleep(0.5)

            time_end = time.time()
            t = time_end - time_start
            # 从硬件读一个压力
            p_s = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器

            self.label.setText(f'{t:.2f}' + "s")
            self.label.repaint()
            self.label_4.setText(f'{p_s:.2f}' + "kPa")
            self.label_4.repaint()

            if t >= 60:
                break
        
        # 10s倒计时，计算最大偏离值
        time_start = time.time()
        pn_max = 0 # 记录偏离值的最大值
        P = [] # 保存10s读的每一个压力值，后续计算平均值
        while True:
            time.sleep(0.5)

            time_end = time.time()
            t = time_end - time_start
            # 从硬件读一个压力
            p_s = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
            P.append(p_s)
            pn_max = max(pn_max, abs(p_s - self.DATA['基准值']))

            self.label_3.setText(f'{t:.2f}' + "s")
            self.label_3.repaint()
            self.label_4.setText(f'{p_s:.2f}' + "kPa")
            self.label_4.repaint()

            if t >= 10:
                break

        # 计算
        self.label_5.setText(str(self.DATA['基准值']))
        self.label_6.setText(f'{pn_max:.2f}')
        p_avg = sum(P) / len(P)
        self.label_7.setText(f'{p_avg:.2f}')

    def f_clear(self):
        # 还原按钮
        self.lineEdit.clear()
        self.label.setText("1min倒计时显示")
        self.label_3.setText("10s倒计时显示")
        self.label_4.setText("实时压力测量值")
        self.label_5.clear()
        self.label_6.clear()
        self.label_7.clear()
    
    def save_file(self):
        # 保存文件
        with open(self.path, 'w', encoding='utf-8') as writers:
            
            writers.write('    设置值: ' + self.label_5.text() + "kPa;\n    偏离设置值最大的示值: " + self.label_6.text()
                          + "kPa\n    差值: " + self.label_7.text() + 'kPa\n')
    
    def closeEvent(self, event):
        # 重载界面关闭事件
        self.father.resize(800, 400)
        event.accept()


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     gui = UI_F()
#     gui.show()
#     sys.exit(app.exec_())
