# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pic_rc
import time, os
import RPi.GPIO as GPIO
import config


class UI_G(QtWidgets.QMainWindow):
    def __init__(self, fa, ADC):
        super(UI_G, self).__init__()
        self.crt_num = None # 当前测的通道序号
        self.DATA = {} # 保存当前页面的数据信息
        self.father = fa # 父界面，即系统主界面
        self.path = './tmp/g.txt' # 当前功能实验结果临时文件
        self.ADC = ADC # 压力传感器
        self.pwm = GPIO.PWM(config.PUMP_PWM, 20000) # 声明一个 加压器对象
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 410)
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.textBrowser_1.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 100, 151, 71))
        self.textBrowser_2.setStyleSheet("background-color:yellow\n"
                                         "\n"
                                         "")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(160, 100, 211, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(7, 6, 201, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 180, 211, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(7, 6, 201, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 170, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(220, 180, 221, 71))
        self.textBrowser_3.setStyleSheet("background-color:yellow\n"
                                         "")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 260, 211, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(7, 6, 201, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 280, 160, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(0, 330, 211, 71))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(7, 6, 201, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 350, 160, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(450, 370, 80, 30))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(700, 370, 80, 30))
        self.pushButton_return.setObjectName("pushButton_return")
        self.label_png = QtWidgets.QLabel(Form)
        self.label_png.setGeometry(QtCore.QRect(450, 0, 330, 210))
        self.label_png.setText("")
        self.label_png.setPixmap(QtGui.QPixmap(":/resources/device.png"))
        self.label_png.setScaledContents(True)
        self.label_png.setObjectName("label_png")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 120, 60, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(450, 260, 331, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 220, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(570, 370, 80, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.frame_2.raise_()
        self.textBrowser_1.raise_()
        self.textBrowser_2.raise_()
        self.frame_3.raise_()
        self.textBrowser_3.raise_()
        self.frame_4.raise_()
        self.pushButton_3.raise_()
        self.frame_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_clear.raise_()
        self.pushButton_return.raise_()
        self.label_png.raise_()
        self.pushButton_2.raise_()
        self.textBrowser.raise_()
        self.pushButton_5.raise_()
        self.pushButton_save.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("气密性检查")
        self.textBrowser_1.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(1)按图连接止血带机通道1和标准器气路，将中号止血袖带卷扎在合适尺寸硬质圆柱上</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)打开压力发生器、压力标准器和止血袖带气路开关1、3和4，关闭其他开关</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(3)设置止血带机处于待机状态(或校准模式)</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：输入止血带机最大工作压力和通道数量后，启动压力发生器并显示压力测量示值</p></body></html>"))
        self.label.setText(_translate("Form", "总通道数量"))
        self.label_2.setText(_translate("Form", "最大工作压力数值kPa"))
        self.label_3.setText(_translate("Form", "当前通道序号"))
        self.pushButton.setText(_translate("Form", "启动压力发生器"))
        self.textBrowser_3.setHtml(_translate("Form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提示：(1)压力到达后，启动1min计时，关闭气路开关1</p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(2)当前通道未出结果前不要操作其他</p></body></html>"))
        self.label_7.setText(_translate("Form", "压力测量值"))
        self.label_8.setText(_translate("Form", "1min计时时间显示"))
        self.pushButton_3.setText(_translate("Form", "1min计时启动键"))
        self.label_11.setText(_translate("Form", "压力测量值"))
        self.label_12.setText(_translate("Form", "10min计时时间显示"))
        self.pushButton_4.setText(_translate("Form", "10min计时启动键"))
        self.pushButton_clear.setText(_translate("Form", "还原"))
        self.pushButton_return.setText(_translate("Form", "返回"))
        self.pushButton_2.setText(_translate("Form", "确认"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "检查结果"))
        self.pushButton_save.setText(_translate("Form", "保存"))

        # -----------------------------------初始化，调整文本框可视-------------------------------------------
        self.textBrowser.hide()
        # --------------------------------------------------------------------------------------------------

        # ----------------------------------------绑定按钮槽函数---------------------------------------------
        self.pushButton_2.clicked.connect(self.g_1)
        self.pushButton.clicked.connect(self.g_2)
        self.pushButton_3.clicked.connect(self.g_3)
        self.pushButton_4.clicked.connect(self.g_4)
        self.pushButton_5.clicked.connect(self.g_over)
        self.pushButton_clear.clicked.connect(self.g_clear)
        self.pushButton_save.clicked.connect(self.save_file)
        # --------------------------------------------------------------------------------------------------

        # 返回主程序
        self.pushButton_return.clicked.connect(lambda: {self.father.show(), self.close()})

        # 创建一个临时txt
        if os.path.exists(self.path):
            os.remove(self.path)
        file = open(self.path, 'w')
        file.close()

    def g_1(self):
        # 输入相应参数
        # 如果是数字，先判断是否填写了，如果填写了再判断是否为数字形式
        # 不符合要求进行对话框提醒
        if self.lineEdit_2.text() == '':
            QMessageBox.information(self, 'info', '请输入最大工作压力')
            return
        else:
            if self.lineEdit_2.text().replace(".", "").isdigit():
                self.DATA['最大工作压力'] = float(self.lineEdit_2.text())
            else:
                QMessageBox.information(self, 'info', '请输入正确参数')
                return
        if self.lineEdit.text() == '':
            self.DATA['通道总数'] = 1
            self.lineEdit.setText("1")
        else:
            if self.lineEdit.text().replace(".", "").isdigit():
                self.DATA['通道总数'] = int(self.lineEdit.text())
            else:
                QMessageBox.information(self, 'info', '请输入正确参数')
                return

    def g_2(self):
        # 先判断是否填了当前通道序号
        if self.lineEdit_4.text() == '':
            QMessageBox.information(self, 'info', '请输入当前通道序号')
            return
        else:
            if self.lineEdit_4.text().replace(".", "").isdigit():
                self.crt_num = int(self.lineEdit_4.text())
                if self.crt_num > self.DATA['通道总数']:
                    QMessageBox.information(self, 'info', '请输入正确通道序号')
                    return
                else:
                    # 启动加压装置
                    GPIO.output(config.PUMP_EN, GPIO.LOW)
                    self.pwm.start(50) # 群里说这个占空比是0~100

                    while True:
                        time.sleep(0.5)
                        p_s = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
                        if p_s >= 0.9 * self.DATA['最大工作压力']:
                            # 停止压力发生器
                            GPIO.output(config.PUMP_EN, GPIO.HIGH) # 给加压器高电平，停止加压
                            self.pwm.stop()
                            time.sleep(0.5)

                            QMessageBox.information(self, 'info', '90%最大压力已达到,启动计时器1min计时,关闭压力发生器气路开关1')
                            break
            else:
                QMessageBox.information(self, 'info', '请输入正确通道序号')
                return

    def g_3(self):
        # 1min倒计时启动
        time_start = time.time()
        while True:
            time.sleep(0.5)
            time_end = time.time()
            tm = time_end - time_start
            # 从硬件读一个压力
            p_s = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
            self.label_9.setText(f'{tm:.2f}' + "s")
            self.label_9.repaint()
            self.label_10.setText(f'{p_s:.2f}' + "kPa")
            self.label_10.repaint()
            if tm >= 60:
                break

    def g_4(self):
        # 10min倒计时启动
        time_start = time.time()
        # 读一个起始压力
        p1 = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
        while True:
            time.sleep(0.5)
            time_end = time.time()
            tm = time_end - time_start
            # 读一个当前压力
            p2 = self.ADC.ADS1256_GetChannalValue(6) * 500 / 0x7fffff  # 高精度传感器
            self.label_13.setText(f'{tm:.2f}' + "s")
            self.label_13.repaint()
            self.label_14.setText(f'{p2:.2f}' + "kPa")
            self.label_14.repaint()
            if tm >= 600:
                k = abs((p2 - p1) / 10)
                self.textBrowser.append("通道" + str(self.crt_num) + "  袖带压力初始值: " + f'{p1:.2f}' + "kPa;10分钟后袖带压力终值: "
                                         + f'{p2:.2f}' + "kPa;压力下降率为" + f'{k:.4f}' + "kPa/min")
                break

    def g_over(self):
        # 检查结果查询按钮
        self.textBrowser.show()

    def g_clear(self):
        # 还原按钮
        self.textBrowser.clear()
        self.textBrowser.hide()
        self.lineEdit_2.clear()
        self.lineEdit.clear()
        self.lineEdit_4.clear()
        self.label_9.clear()
        self.label_10.clear()
        self.label_13.clear()
        self.label_14.clear()
    
    def save_file(self):
        # 保存文件
        with open(self.path, 'w', encoding='utf-8') as writers:
            
            content = self.textBrowser.toPlainText().replace('\n', ';\n      ')
            writers.write(content)
    
    def closeEvent(self, event):
        # 重载界面关闭事件
        self.father.resize(800, 400)
        event.accept()


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     gui = UI_G()
#     gui.show()
#     sys.exit(app.exec_())
